apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  labels:
    app.kubernetes.io/instance: kyverno-policies
  name: ImageLatestTag
spec:
  validationFailureAction: enforce
  rules:
    - name: check-image-latest-tag
      match:
        resources:
          kinds:
            - Deployment
      validate:
        message: 'Every container in the Deployment must use an image tagged with "latest".'
        pattern:
          spec:
            template:
              spec:
                containers:
                  - image: '*:latest'
